In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
df = pd.read_csv('Grocery.csv', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,frankfurter,sausage,liver loaf,ham,chicken,beef,citrus fruit,tropical fruit,root vegetables,other vegetables,...,roll products,flour,pasta,margarine,specialty fat,sugar,soups,skin care,hygiene articles,candles
1,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(9836, 32)

In [5]:
basket_sets = pd.get_dummies(df)

In [6]:
basket_sets.head(5)

,0_Instant food products,0_UHT-milk,0_abrasive cleaner,0_artif. sweetener,0_baby cosmetics,0_bags,0_baking powder,0_bathroom cleaner,0_beef,0_berries,...,27_chocolate,27_hygiene articles,27_napkins,27_sugar,28_cooking chocolate,28_house keeping products,28_soups,29_skin care,30_hygiene articles,31_candles
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
basket_sets.tail(5)

,0_Instant food products,0_UHT-milk,0_abrasive cleaner,0_artif. sweetener,0_baby cosmetics,0_bags,0_baking powder,0_bathroom cleaner,0_beef,0_berries,...,27_chocolate,27_hygiene articles,27_napkins,27_sugar,28_cooking chocolate,28_house keeping products,28_soups,29_skin care,30_hygiene articles,31_candles
9831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9835,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#applying apriori algorithm to generate rules
frequent_itemsets = apriori(basket_sets, min_support=0.003, use_colnames=True)
frequent_itemsets.tail
frequent_itemsets.shape

(487, 2)

In [9]:
#calculating confidence and lift for the genrated rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedants,consequents,support,confidence,lift
0,(0_beef),(1_citrus fruit),0.030907,0.157895,6.471053
1,(1_citrus fruit),(0_beef),0.024400,0.200000,6.471053
2,(0_beef),(1_other vegetables),0.030907,0.105263,1.882488
3,(1_other vegetables),(0_beef),0.055917,0.058182,1.882488
4,(0_beef),(1_root vegetables),0.030907,0.180921,4.646317
5,(1_root vegetables),(0_beef),0.038939,0.143603,4.646317
6,(0_beef),(2_other vegetables),0.030907,0.115132,2.728757
7,(2_other vegetables),(0_beef),0.042192,0.084337,2.728757
8,(0_beef),(2_whole milk),0.030907,0.098684,1.918296
9,(2_whole milk),(0_beef),0.051444,0.059289,1.918296
10,(0_beef),(3_whole milk),0.030907,0.105263,3.286884
11,(3_whole milk),(0_beef),0.032025,0.101587,3.286884
12,(1_soda),(0_bottled water),0.028772,0.141343,8.177926
13,(0_bottled water),(1_soda),0.017283,0.235294,8.177926
14,(1_other vegetables),(0_chicken),0.055917,0.056364,1.782613
15,(0_chicken),(1_other vegetables),0.031619,0.099678,1.782613
16,(1_pork),(0_chicken),0.013725,0.251852,7.965321
17,(0_chicken),(1_pork),0.031619,0.109325,7.965321
18,(2_other vegetables),(0_chicken),0.042192,0.077108,2.438709
19,(0_chicken),(2_other vegetables),0.031619,0.102894,2.438709
20,(2_whole milk),(0_chicken),0.051444,0.081028,2.562663
21,(0_chicken),(2_whole milk),0.031619,0.131833,2.562663
22,(3_other vegetables),(0_chicken),0.025824,0.122047,3.859989
23,(0_chicken),(3_other vegetables),0.031619,0.099678,3.859989
24,(1_other vegetables),(0_citrus fruit),0.055917,0.090909,1.973911
25,(0_citrus fruit),(1_other vegetables),0.046055,0.110375,1.973911
26,(1_pip fruit),(0_citrus fruit),0.023485,0.181818,3.947823
27,(0_citrus fruit),(1_pip fruit),0.046055,0.092715,3.947823
28,(1_root vegetables),(0_citrus fruit),0.038939,0.086162,1.870835
29,(0_citrus fruit),(1_root vegetables),0.046055,0.072848,1.870835
...,...,...,...,...,...
310,"(2_pip fruit, 0_citrus fruit)",(1_tropical fruit),0.003152,1.000000,27.707042
311,"(2_pip fruit, 1_tropical fruit)",(0_citrus fruit),0.007930,0.397436,8.629535
312,"(0_citrus fruit, 1_tropical fruit)",(2_pip fruit),0.011590,0.271930,18.195250
313,(2_pip fruit),"(0_citrus fruit, 1_tropical fruit)",0.014945,0.210884,18.195250
314,(0_citrus fruit),"(2_pip fruit, 1_tropical fruit)",0.046055,0.068433,8.629535
315,(1_tropical fruit),"(2_pip fruit, 0_citrus fruit)",0.036092,0.087324,27.707042
316,"(0_root vegetables, 2_whole milk)",(1_other vegetables),0.004168,0.780488,13.957960
317,"(0_root vegetables, 1_other vegetables)",(2_whole milk),0.008133,0.400000,7.775494
318,"(1_other vegetables, 2_whole milk)",(0_root vegetables),0.018300,0.177778,6.071605
319,(0_root vegetables),"(1_other vegetables, 2_whole milk)",0.029280,0.111111,6.071605
320,(2_whole milk),"(0_root vegetables, 1_other vegetables)",0.051444,0.063241,7.775494
321,(1_other vegetables),"(0_root vegetables, 2_whole milk)",0.055917,0.058182,13.957960
322,"(1_other vegetables, 2_whole milk)",(3_yogurt),0.018300,0.177778,8.656546
323,"(1_other vegetables, 3_yogurt)",(2_whole milk),0.004778,0.680851,13.234884
324,"(3_yogurt, 2_whole milk)",(1_other vegetables),0.007422,0.438356,7.839402
325,(1_other vegetables),"(3_yogurt, 2_whole milk)",0.055917,0.058182,7.839402
326,(2_whole milk),"(1_other vegetables, 3_yogurt)",0.051444,0.063241,13.234884
327,(3_yogurt),"(1_other vegetables, 2_whole milk)",0.020537,0.158416,8.656546
328,"(1_root vegetables, 2_other vegetables)",(3_whole milk),0.012505,0.414634,12.947116
329,"(1_root vegetables, 3_whole milk)",(2_other vegetables),0.006202,0.836066,19.815761
330,"(2_other vegetables, 3_whole milk)",(1_root vegetables),0.017283,0.300000,7.704439
331,(1_root vegetables),"(2_other vegetables, 3_whole milk)",0.038939,0.133159,7.704439
332,(2_other vegetables),"(1_root vegetables, 3_whole milk)",0.042192,0.122892,19.815761
333,(3_whole milk),"(1_root vegetables, 2_other vegetables)",0.032025,0.161905,12.947116
334,"(3_other vegetables, 4_whole milk)",(2_root vegetables),0.010573,0.394231,18.642567
335,"(3_other vegetables, 2_root vegetables)",(4_whole milk),0.008845,0.471264,31.109774
336,"(4_whole milk, 2_root vegetables)",(3_other vegetables),0.004982,0.836735,32.402057
337,(3_other vegetables),"(4_whole milk, 2_root vegetables)",0.025824,0.161417,32.402057
338,(4_whole milk),"(3_other vegetables, 2_root vegetables)",0.015148,0.275168,31.109774
339,(2_root vegetables),"(3_other vegetables, 4_whole milk)",0.021147,0.197115,18.642567

In [10]:
#selecting the rules with lift >1
rules[ (rules['lift'] >= 1 ) &
       (rules['confidence'] >= 0.5) ]

,antecedants,consequents,support,confidence,lift
46,(1_sausage),(0_frankfurter),0.010167,1.000000,16.929432
99,(1_ham),(0_sausage),0.006507,0.671875,8.010379
102,(1_meat),(0_sausage),0.007625,0.586667,6.994489
212,(2_pip fruit),(1_tropical fruit),0.014945,0.530612,14.701696
225,(2_curd),(1_whole milk),0.010167,0.510000,7.670275
235,(2_onions),(3_other vegetables),0.007523,0.513514,19.885508
237,(3_whole milk),(2_other vegetables),0.032025,0.539683,12.791126
254,(3_pip fruit),(2_tropical fruit),0.007320,0.583333,40.123543
258,(3_butter),(2_whole milk),0.009150,0.666667,12.959157
260,(3_curd),(2_whole milk),0.008845,0.586207,11.395121
283,(4_whole milk),(3_other vegetables),0.015148,0.697987,27.029118
286,(4_butter),(3_whole milk),0.006812,0.686567,21.438332
302,(5_whole milk),(4_other vegetables),0.008845,0.793103,65.008046
303,(4_other vegetables),(5_whole milk),0.012200,0.575000,65.008046
308,(5_other vegetables),(6_whole milk),0.006913,0.588235,118.079232
309,(6_whole milk),(5_other vegetables),0.004982,0.816327,118.079232
310,"(2_pip fruit, 0_citrus fruit)",(1_tropical fruit),0.003152,1.000000,27.707042
316,"(0_root vegetables, 2_whole milk)",(1_other vegetables),0.004168,0.780488,13.957960
323,"(1_other vegetables, 3_yogurt)",(2_whole milk),0.004778,0.680851,13.234884
329,"(1_root vegetables, 3_whole milk)",(2_other vegetables),0.006202,0.836066,19.815761
336,"(4_whole milk, 2_root vegetables)",(3_other vegetables),0.004982,0.836735,32.402057